export const REQUEST_TIMESERIES = 'REQUEST_TIMESERIES';
export const LOADED_TIMESERIES = 'LOADED_TIMESERIES';
export const REQUEST_STREAMDATA = 'REQUEST_STREAMDATA';
export const LOADED_STREAMDATA = 'LOADED_STREAMDATA';
